name: rss
on: [push]
jobs:
  get-releases:
    runs-on: ubuntu-latest
    container:
      image: alpine/xml:latest
    outputs:
      releases: ${{ steps.get.outputs.releases }}
    steps:
      - id: get
        run: |
          curl -O https://cloud.google.com/feeds/gcp-release-notes.xml
          releases=$(cat gcp-release-notes.xml | xq -c '.feed.entry | map(select(.content."#text" | ascii_upcase | contains("LOOKER"))) | map({title: .title, link: .link."@href"})')
          echo ${releases}
          echo "releases='${releases}'" >> $GITHUB_OUTPUT

  create-issue:
    needs: get-releases
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.get-releases.outputs.releases }}
